### PR TITLE
what it does

### PR DESCRIPTION
**Pull request by NotJustMeHere**
It's still obfuscated but still in order.

### CODE REVIEW

**Comment by ThetruePyrobyte** [comment]
Thanks

**Comment by ThetruePyrobyte** [comment]
Any idea what it does, I have a weak idea?

**Comment by ThetruePyrobyte** [comment]
Thanks a lot, this simplifies the code a lot (even though it's practically the same.)

**Comment by Bremy500** [comment]
what is this stuff iy makes no sense
________________________________

**Pull request merged**
